### ISSUE TITLE
wget static data is failing

### ISSUE THREAD

**Issue by paultag** [rspeer/solvertools#2]
```
wget https://tools.ireproof.org/static/solvertools-data-2019.tar.gz
--2019-01-18 17:36:28--  https://tools.ireproof.org/static/solvertools-data-2019.tar.gz
Resolving tools.ireproof.org (tools.ireproof.org)... 34.237.166.150
Connecting to tools.ireproof.org (tools.ireproof.org)|34.237.166.150|:443... failed: Connection refused.
```

thank you for maintaining this invaluable resource!

**Comment by lambdaloop** [comment]
Apparently this works if you use http instead of https:
`wget http://tools.ireproof.org/static/solvertools-data-2019.tar.gz`

**Comment by paultag** [comment]
@lambdaloop right you are, thank you!

**Comment by paultag** [comment]
this was seemingly fixed in the readme at https://github.com/rspeer/solvertools/commit/f53284f6eadaee4fe0bcc6a3e390bc4fd6d3210b
